/* samples.js: written by tools/make-sounds.js. The recorded effects sound.js may load; anything not here is synthesised. */
(function () {
  'use strict';
  window.UndercroftSamples = {
    "swing": { file: "audio/undercroft/swing.mp3", volume: 0.5 },
    "swingheavy": { file: "audio/undercroft/swingheavy.mp3", volume: 0.6 },
    "swingquick": { file: "audio/undercroft/swingquick.mp3", volume: 0.45 },
    "whip": { file: "audio/undercroft/whip.mp3", volume: 0.6 },
    "shot": { file: "audio/undercroft/shot.mp3", volume: 0.5 },
    "bolt": { file: "audio/undercroft/bolt.mp3", volume: 0.5 },
    "hit": { file: "audio/undercroft/hit.mp3", volume: 0.7 },
    "heavy": { file: "audio/undercroft/heavy.mp3", volume: 0.85 },
    "clink": { file: "audio/undercroft/clink.mp3", volume: 0.6 },
    "jump": { file: "audio/undercroft/jump.mp3", volume: 0.35 },
    "flip": { file: "audio/undercroft/flip.mp3", volume: 0.4 },
    "land": { file: "audio/undercroft/land.mp3", volume: 0.4 },
    "dash": { file: "audio/undercroft/dash.mp3", volume: 0.5 },
    "blink": { file: "audio/undercroft/blink.mp3", volume: 0.55 },
    "charge": { file: "audio/undercroft/charge.mp3", volume: 0.6 },
    "flare": { file: "audio/undercroft/flare.mp3", volume: 0.6 },
    "hurt": { file: "audio/undercroft/hurt.mp3", volume: 0.7 },
    "death": { file: "audio/undercroft/death.mp3", volume: 0.8 },
    "flamelost": { file: "audio/undercroft/flamelost.mp3", volume: 0.7 },
    "castember": { file: "audio/undercroft/castember.mp3", volume: 0.7 },
    "castfrost": { file: "audio/undercroft/castfrost.mp3", volume: 0.65 },
    "caststorm": { file: "audio/undercroft/caststorm.mp3", volume: 0.65 },
    "castbloom": { file: "audio/undercroft/castbloom.mp3", volume: 0.6 },
    "freeze": { file: "audio/undercroft/freeze.mp3", volume: 0.55 },
    "pickup": { file: "audio/undercroft/pickup.mp3", volume: 0.6 },
    "chest": { file: "audio/undercroft/chest.mp3", volume: 0.7 },
    "perk": { file: "audio/undercroft/perk.mp3", volume: 0.75 },
    "legend": { file: "audio/undercroft/legend.mp3", volume: 0.85 },
    "bell": { file: "audio/undercroft/bell.mp3", volume: 0.7 },
    "font": { file: "audio/undercroft/font.mp3", volume: 0.7 },
    "select": { file: "audio/undercroft/select.mp3", volume: 0.4 },
    "confirm": { file: "audio/undercroft/confirm.mp3", volume: 0.5 },
    "door": { file: "audio/undercroft/door.mp3", volume: 0.7 },
    "portal": { file: "audio/undercroft/portal.mp3", volume: 0.8 },
    "portalhum": { file: "audio/undercroft/portalhum.mp3", volume: 0.35, loop: true },
    "brazier": { file: "audio/undercroft/brazier.mp3", volume: 0.7 },
    "crack": { file: "audio/undercroft/crack.mp3", volume: 0.5 },
    "boom": { file: "audio/undercroft/boom.mp3", volume: 0.9 },
    "roar": { file: "audio/undercroft/roar.mp3", volume: 0.8 },
    "roargolem": { file: "audio/undercroft/roargolem.mp3", volume: 0.85 },
    "roarwyrm": { file: "audio/undercroft/roarwyrm.mp3", volume: 0.85 },
    "roarherald": { file: "audio/undercroft/roarherald.mp3", volume: 0.8 },
    "roarthorn": { file: "audio/undercroft/roarthorn.mp3", volume: 0.85 },
    "roarorrery": { file: "audio/undercroft/roarorrery.mp3", volume: 0.85 },
    "roarlightless": { file: "audio/undercroft/roarlightless.mp3", volume: 0.9 },
    "breath": { file: "audio/undercroft/breath.mp3", volume: 0.7 },
    "gust": { file: "audio/undercroft/gust.mp3", volume: 0.65 },
    "icicle": { file: "audio/undercroft/icicle.mp3", volume: 0.6 },
    "thunder": { file: "audio/undercroft/thunder.mp3", volume: 0.85 },
    "beam": { file: "audio/undercroft/beam.mp3", volume: 0.6 },
    "clap": { file: "audio/undercroft/clap.mp3", volume: 0.9 },
    "lash": { file: "audio/undercroft/lash.mp3", volume: 0.7 },
    "roots": { file: "audio/undercroft/roots.mp3", volume: 0.7 },
    "spit": { file: "audio/undercroft/spit.mp3", volume: 0.55 },
    "moon": { file: "audio/undercroft/moon.mp3", volume: 0.85 },
    "eclipse": { file: "audio/undercroft/eclipse.mp3", volume: 0.75 },
    "shatter": { file: "audio/undercroft/shatter.mp3", volume: 0.85 },
    "victory": { file: "audio/undercroft/victory.mp3", volume: 0.85 }
  };
})();
