/* make-rooms.js — stamps the room pages from one template.

   Rooms 6 to 15 are each a page of their own. Their mastheads, footers and
   the floor plan in the hall all have to agree with each other, so they are
   written from the single list in tools/rooms.js instead of ten times by hand.

   This is an authoring tool, not a build step: its output is plain HTML that
   is committed and served as-is. Run it after editing tools/rooms.js:

       node tools/make-rooms.js

   It rewrites rooms/<slug>.html for every room marked ready, and the block
   between the plan markers in index.html. Edit copy in rooms.js, not in the
   generated pages. */
'use strict';

var fs = require('fs');
var path = require('path');
var root = path.join(__dirname, '..');
var data = require('./rooms.js');

var TOTAL = data.hall.length + data.rooms.length;
var WORDS = [null, 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen',
  'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'twenty-one', 'twenty-two', 'twenty-three',
  'twenty-four', 'twenty-five', 'twenty-six', 'twenty-seven', 'twenty-eight', 'twenty-nine', 'thirty', 'thirty-one', 'thirty-two',
  'thirty-three', 'thirty-four', 'thirty-five', 'thirty-six', 'thirty-seven', 'thirty-eight', 'thirty-nine', 'forty'];
var ready = data.rooms.filter(function (room) { return room.ready; });

function escapeHtml(text) {
  return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function indent(html, spaces) {
  var pad = new Array(spaces + 1).join(' ');
  return html.trim().split('\n').map(function (line) { return line.trim() ? pad + line : ''; }).join('\n');
}

/* ---- one room page ---- */

function page(room, index) {
  var previous = index > 0 ? ready[index - 1] : null;
  var next = index < ready.length - 1 ? ready[index + 1] : null;
  var lastHall = data.hall[data.hall.length - 1];
  var back = previous
    ? { href: previous.slug + '.html', label: 'Previous room', name: previous.number + '. ' + previous.title }
    : { href: '../index.html#' + lastHall.id, label: 'Previous room', name: lastHall.number + '. ' + lastHall.title + ', in the hall' };
  var onward = next
    ? { href: next.slug + '.html', label: 'Next room', name: next.number + '. ' + next.title }
    : { href: '../index.html', label: 'Round again', name: data.hall[0].number + '. ' + data.hall[0].title + ', at the entrance' };
  var scripts = ['../js/core.js'].concat((room.scripts || []).map(function (s) { return '../js/' + s; }), ['../js/rooms/' + room.slug + '.js']);
  // A room with a game in it is played by two machines that must run the same code to the letter. Its scripts are
  // asked for by what they hash to, so that a browser never mixes an old file with a new page, and the page carries
  // the hash so that two players can tell each other which game they have (net.js refuses a mismatch). Run this
  // tool again after editing any of them; tools/lockstep.html says when the stamp is stale.
  var build = '';
  if (room.scripts && room.stamp) {
    var h = 2166136261;
    scripts.slice(1).forEach(function (src) {
      var text = fs.readFileSync(path.join(root, 'rooms', src), 'utf8').replace(/\r/g, '');
      for (var i = 0; i < text.length; i++) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619) >>> 0; }
    });
    build = ('0000000' + h.toString(16)).slice(-8);
    scripts = scripts.map(function (src, k) { return k ? src + '?v=' + build : src; });
  }

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
    '  <title>' + escapeHtml(room.title) + ' — Look, no hands.</title>',
    '  <meta name="description" content="' + escapeHtml(room.description) + '">',
    '  <meta name="theme-color" content="#000000">',
    '  <meta name="color-scheme" content="dark">',
    '',
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,100..900,0..100,0..1;1,9..144,100..900,0..100,0..1&family=Hanken+Grotesk:wght@400;500;600&display=swap" rel="stylesheet">',
    '  <link rel="stylesheet" href="../css/style.css">',
    '</head>',
    '<body>',
    '  <!-- Generated by tools/make-rooms.js from tools/rooms.js. Edit there. -->',
    '  <a class="skip-link" href="#work">Skip to the work</a>',
    '',
    '  <header class="masthead">',
    '    <a class="masthead__title" href="../index.html">Look, no hands.</a>',
    '    <nav class="masthead__turn" aria-label="Previous and next room">',
    '      <a class="masthead__arrow" href="' + back.href + '" rel="prev" data-way="previous" aria-label="Previous room: ' + escapeHtml(back.name) + '">&larr;</a>',
    '      <p class="masthead__where"><span class="masthead__word">Room </span>' + room.number + '<span class="masthead__word"> of </span><span class="masthead__slash" aria-hidden="true"> / </span>' + TOTAL + '</p>',
    '      <a class="masthead__arrow" href="' + onward.href + '" rel="next" data-way="next" aria-label="' + (next ? 'Next room: ' : 'Round again: ') + escapeHtml(onward.name) + '">&rarr;</a>',
    '    </nav>',
    '    <a class="masthead__plan" href="../index.html#plan">Floor plan</a>',
    '    <button class="btn btn--quiet motion-toggle" type="button" aria-label="Pause motion" data-motion-toggle><span data-motion-verb>Pause</span><span class="motion-toggle__noun">&nbsp;motion</span></button>',
    '  </header>',
    '',
    '  <main>',
    '    <section class="room room--solo room--' + room.slug + '" id="work" data-room>',
    '      <div class="stage" data-work="' + room.slug + '"' + (build ? ' data-build="' + build + '"' : '') + (room.stageAttributes ? ' ' + room.stageAttributes : '') + '>',
    '        <canvas class="stage__canvas" role="img" aria-label="' + escapeHtml(room.canvasLabel) + '"></canvas>',
    '        <p class="stage__notice"></p>',
    '      </div>',
    '      <div class="label">',
    '        <h1 class="label__title">' + escapeHtml(room.title) + '</h1>',
    '        <p class="label__medium">' + room.medium + '</p>',
    // a room that is played rather than read (36) puts its controls before its long label
    room.controls && room.controlsFirst ? indent(room.controls, 8) : '        <p class="label__text">' + room.text + '</p>',
    room.controls && room.controlsFirst ? (room.hideText ? '' : '        <p class="label__text">' + room.text + '</p>') : room.controls ? indent(room.controls, 8) : '',
    '        <a class="label__next" href="' + onward.href + '"><span class="label__next-label">' + (next ? 'Next room' : 'Round again') + '</span><span class="label__next-name">' + escapeHtml(onward.name) + '</span><span class="label__next-arrow" aria-hidden="true">&rarr;</span></a>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="wall">',
    '      <p class="wall__text">' + room.wall + '</p>',
    '    </section>',
    '',
    '    <nav class="ways" aria-label="Other rooms">',
    '      <a class="ways__link" href="' + back.href + '"><span class="ways__label">' + back.label + '</span><span class="ways__name">' + escapeHtml(back.name) + '</span></a>',
    '      <a class="ways__link ways__link--plan" href="../index.html#plan"><span class="ways__label">All ' + TOTAL + ' rooms</span><span class="ways__name">Floor plan</span></a>',
    '      <a class="ways__link ways__link--onward" href="' + onward.href + '"><span class="ways__label">' + onward.label + '</span><span class="ways__name">' + escapeHtml(onward.name) + '</span></a>',
    '    </nav>',
    '  </main>',
    '',
    '  <noscript>',
    '    <p class="noscript">This work is computed live, so it needs JavaScript to run. Nothing here is a recording that could play without it.</p>',
    '  </noscript>',
    ''
  ].concat(scripts.map(function (src) { return '  <script src="' + src + '"></script>'; }), ['</body>', '</html>', ''])
    .filter(function (line, i, all) { return !(line === '' && all[i - 1] === ''); })
    .join('\n');
}

/* ---- the floor plan in the hall ---- */

function plan() {
  if (!ready.length) return '';
  var lines = [
    '    <section class="plan" id="plan" aria-labelledby="plan-heading">',
    '      <h2 class="plan__heading" id="plan-heading">The rest of the building</h2>',
    '      <p class="plan__intro">' + data.planIntro.replace('{are}', ready.length === 1 ? 'is' : 'are').replace('{count}', WORDS[ready.length] || String(ready.length)) + '</p>',
    '      <ol class="plan__hall" aria-label="The hall">'
  ];
  data.hall.forEach(function (room) {
    lines.push('        <li><a class="plan__door" href="#' + room.id + '"><span class="plan__num">' + room.number + '</span><span class="plan__door-name">' + escapeHtml(room.title) + '</span></a></li>');
  });
  lines.push('      </ol>', '      <ol class="plan__rooms" aria-label="Rooms ' + ready[0].number + ' to ' + ready[ready.length - 1].number + '">');
  ready.forEach(function (room) {
    lines.push(
      '        <li class="plan__room">',
      '          <a class="plan__link" href="rooms/' + room.slug + '.html">',
      '            <canvas class="plan__glyph" data-glyph="' + room.slug + '" aria-hidden="true"></canvas>',
      '            <span class="plan__num">' + room.number + '</span>',
      '            <span class="plan__title">' + escapeHtml(room.title) + '</span>',
      '            <span class="plan__line">' + escapeHtml(room.line) + '</span>',
      '          </a>',
      '        </li>'
    );
  });
  lines.push('      </ol>', '    </section>');
  return lines.join('\n');
}

/* ---- write everything ---- */

var roomsDir = path.join(root, 'rooms');
if (!fs.existsSync(roomsDir)) fs.mkdirSync(roomsDir);
fs.readdirSync(roomsDir).forEach(function (file) {
  var slug = file.replace(/\.html$/, '');
  if (/\.html$/.test(file) && !ready.some(function (room) { return room.slug === slug; })) fs.unlinkSync(path.join(roomsDir, file));
});
ready.forEach(function (room, index) {
  fs.writeFileSync(path.join(roomsDir, room.slug + '.html'), page(room, index));
});

var indexPath = path.join(root, 'index.html');
var html = fs.readFileSync(indexPath, 'utf8');
var START = '<!-- plan:start -->', END = '<!-- plan:end -->';
var from = html.indexOf(START), to = html.indexOf(END);
if (from < 0 || to < 0) throw new Error('index.html has lost its plan markers');
var block = plan();
html = html.slice(0, from + START.length) + '\n' + (block ? block + '\n' : '') + '    ' + html.slice(to);
fs.writeFileSync(indexPath, html);

/* ---- the corpus: every wall text in the building, for the docent to learn from ----

   Written to js/corpus.js so that room 35 can read the whole exhibition
   without fetching anything, which keeps it working from a file:// URL. */

function plain(html) {
  return String(html || '')
    .replace(/<[^>]+>/g, '')
    .replace(/&rarr;|&amp;|&nbsp;/g, function (m) { return m === '&amp;' ? '&' : m === '&nbsp;' ? ' ' : '→'; })
    .replace(/\s+/g, ' ')
    .trim();
}
var corpus = { titles: [], labels: [] };
// the hall's five labels live in index.html
var hallLabels = html.split('<div class="label').slice(1);
hallLabels.forEach(function (chunk) {
  var title = (chunk.match(/label__title">([\s\S]*?)<\/h2>/) || [])[1];
  var medium = (chunk.match(/label__medium">([\s\S]*?)<\/p>/) || [])[1];
  var texts = [];
  chunk.replace(/label__text(?:[^"]*)">([\s\S]*?)<\/p>/g, function (m, t) { texts.push(plain(t)); return m; });
  if (!title) return;
  corpus.titles.push(plain(title));
  corpus.labels.push({ title: plain(title), line: '', description: '', medium: plain(medium), text: texts.join(' '), wall: '' });
});
ready.forEach(function (room) {
  corpus.titles.push(room.title);
  corpus.labels.push({ title: room.title, line: plain(room.line), description: plain(room.description), medium: plain(room.medium), text: plain(room.text), wall: plain(room.wall) });
});
fs.writeFileSync(path.join(root, 'js', 'corpus.js'),
  '/* corpus.js: every wall text in the building, written by tools/make-rooms.js. Do not edit by hand. */\n' +
  'window.CORPUS = ' + JSON.stringify(corpus, null, 1).replace(/\n\s*/g, ' ') + ';\n');

console.log('rooms written: ' + (ready.map(function (room) { return room.number + ' ' + room.slug; }).join(', ') || 'none') + '; floor plan ' + (block ? 'updated' : 'empty') + '; corpus of ' + corpus.labels.length + ' labels');
