/* make-rooms.js — stamps the room pages from one template.

   Rooms 6 to 15 are each a page of their own. Their mastheads, footers and
   the floor plan in the hall all have to agree with each other, so they are
   written from the single list in tools/rooms.js instead of ten times by hand.

   This is an authoring tool, not a build step: its output is plain HTML that
   is committed and served as-is. Run it after editing tools/rooms.js:

       node tools/make-rooms.js

   It rewrites rooms/<slug>.html for every room marked ready, and the block
   between the plan markers in index.html. Edit copy in rooms.js, not in the
   generated pages. */
'use strict';

var fs = require('fs');
var path = require('path');
var root = path.join(__dirname, '..');
var data = require('./rooms.js');

var TOTAL = data.hall.length + data.rooms.length;
var ready = data.rooms.filter(function (room) { return room.ready; });

function escapeHtml(text) {
  return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function indent(html, spaces) {
  var pad = new Array(spaces + 1).join(' ');
  return html.trim().split('\n').map(function (line) { return line.trim() ? pad + line : ''; }).join('\n');
}

/* ---- one room page ---- */

function page(room, index) {
  var previous = index > 0 ? ready[index - 1] : null;
  var next = index < ready.length - 1 ? ready[index + 1] : null;
  var lastHall = data.hall[data.hall.length - 1];
  var back = previous
    ? { href: previous.slug + '.html', label: 'Previous room', name: previous.number + '. ' + previous.title }
    : { href: '../index.html#' + lastHall.id, label: 'Previous room', name: lastHall.number + '. ' + lastHall.title + ', in the hall' };
  var onward = next
    ? { href: next.slug + '.html', label: 'Next room', name: next.number + '. ' + next.title }
    : { href: '../index.html', label: 'Last room', name: 'Back to the entrance' };
  var scripts = ['../js/core.js'].concat((room.scripts || []).map(function (s) { return '../js/' + s; }), ['../js/rooms/' + room.slug + '.js']);

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
    '  <title>' + escapeHtml(room.title) + ' — Look, no hands.</title>',
    '  <meta name="description" content="' + escapeHtml(room.description) + '">',
    '  <meta name="theme-color" content="#000000">',
    '  <meta name="color-scheme" content="dark">',
    '',
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,100..900,0..100,0..1;1,9..144,100..900,0..100,0..1&family=Hanken+Grotesk:wght@400;500;600&display=swap" rel="stylesheet">',
    '  <link rel="stylesheet" href="../css/style.css">',
    '</head>',
    '<body>',
    '  <!-- Generated by tools/make-rooms.js from tools/rooms.js. Edit there. -->',
    '  <a class="skip-link" href="#work">Skip to the work</a>',
    '',
    '  <header class="masthead">',
    '    <a class="masthead__title" href="../index.html">Look, no hands.</a>',
    '    <p class="masthead__where">Room ' + room.number + ' of ' + TOTAL + '</p>',
    '    <a class="masthead__plan" href="../index.html#plan">Floor plan</a>',
    '    <button class="btn btn--quiet motion-toggle" type="button" aria-label="Pause motion" data-motion-toggle><span data-motion-verb>Pause</span><span class="motion-toggle__noun">&nbsp;motion</span></button>',
    '  </header>',
    '',
    '  <main>',
    '    <section class="room room--solo room--' + room.slug + '" id="work" data-room>',
    '      <div class="stage" data-work="' + room.slug + '"' + (room.stageAttributes ? ' ' + room.stageAttributes : '') + '>',
    '        <canvas class="stage__canvas" role="img" aria-label="' + escapeHtml(room.canvasLabel) + '"></canvas>',
    '        <p class="stage__notice"></p>',
    '      </div>',
    '      <div class="label">',
    '        <h1 class="label__title">' + escapeHtml(room.title) + '</h1>',
    '        <p class="label__medium">' + room.medium + '</p>',
    '        <p class="label__text">' + room.text + '</p>',
    room.controls ? indent(room.controls, 8) : '',
    '      </div>',
    '    </section>',
    '',
    '    <section class="wall">',
    '      <p class="wall__text">' + room.wall + '</p>',
    '    </section>',
    '',
    '    <nav class="ways" aria-label="Other rooms">',
    '      <a class="ways__link" href="' + back.href + '"><span class="ways__label">' + back.label + '</span><span class="ways__name">' + escapeHtml(back.name) + '</span></a>',
    '      <a class="ways__link ways__link--plan" href="../index.html#plan"><span class="ways__label">All ' + TOTAL + ' rooms</span><span class="ways__name">Floor plan</span></a>',
    '      <a class="ways__link ways__link--onward" href="' + onward.href + '"><span class="ways__label">' + onward.label + '</span><span class="ways__name">' + escapeHtml(onward.name) + '</span></a>',
    '    </nav>',
    '  </main>',
    '',
    '  <noscript>',
    '    <p class="noscript">This work is computed live, so it needs JavaScript to run. Nothing here is a recording that could play without it.</p>',
    '  </noscript>',
    ''
  ].concat(scripts.map(function (src) { return '  <script src="' + src + '"></script>'; }), ['</body>', '</html>', ''])
    .filter(function (line, i, all) { return !(line === '' && all[i - 1] === ''); })
    .join('\n');
}

/* ---- the floor plan in the hall ---- */

function plan() {
  if (!ready.length) return '';
  var lines = [
    '    <section class="plan" id="plan" aria-labelledby="plan-heading">',
    '      <h2 class="plan__heading" id="plan-heading">The rest of the building</h2>',
    '      <p class="plan__intro">' + data.planIntro.replace('{count}', String(ready.length)) + '</p>',
    '      <ol class="plan__hall" aria-label="The hall">'
  ];
  data.hall.forEach(function (room) {
    lines.push('        <li><a class="plan__door" href="#' + room.id + '"><span class="plan__num">' + room.number + '</span><span class="plan__door-name">' + escapeHtml(room.title) + '</span></a></li>');
  });
  lines.push('      </ol>', '      <ol class="plan__rooms" aria-label="Rooms ' + ready[0].number + ' to ' + ready[ready.length - 1].number + '">');
  ready.forEach(function (room) {
    lines.push(
      '        <li class="plan__room">',
      '          <a class="plan__link" href="rooms/' + room.slug + '.html">',
      '            <canvas class="plan__glyph" data-glyph="' + room.slug + '" aria-hidden="true"></canvas>',
      '            <span class="plan__num">' + room.number + '</span>',
      '            <span class="plan__title">' + escapeHtml(room.title) + '</span>',
      '            <span class="plan__line">' + escapeHtml(room.line) + '</span>',
      '          </a>',
      '        </li>'
    );
  });
  lines.push('      </ol>', '    </section>');
  return lines.join('\n');
}

/* ---- write everything ---- */

var roomsDir = path.join(root, 'rooms');
if (!fs.existsSync(roomsDir)) fs.mkdirSync(roomsDir);
fs.readdirSync(roomsDir).forEach(function (file) {
  var slug = file.replace(/\.html$/, '');
  if (/\.html$/.test(file) && !ready.some(function (room) { return room.slug === slug; })) fs.unlinkSync(path.join(roomsDir, file));
});
ready.forEach(function (room, index) {
  fs.writeFileSync(path.join(roomsDir, room.slug + '.html'), page(room, index));
});

var indexPath = path.join(root, 'index.html');
var html = fs.readFileSync(indexPath, 'utf8');
var START = '<!-- plan:start -->', END = '<!-- plan:end -->';
var from = html.indexOf(START), to = html.indexOf(END);
if (from < 0 || to < 0) throw new Error('index.html has lost its plan markers');
var block = plan();
html = html.slice(0, from + START.length) + '\n' + (block ? block + '\n' : '') + '    ' + html.slice(to);
fs.writeFileSync(indexPath, html);

console.log('rooms written: ' + (ready.map(function (room) { return room.number + ' ' + room.slug; }).join(', ') || 'none') + '; floor plan ' + (block ? 'updated' : 'empty'));
